### ISSUE TITLE
CONNECTUSER is unusable: engine name & version missing, username  from server missing

### ISSUE THREAD

**Issue by abma** [spring/LobbyProtocol#19]
engine name & version needed!

**Comment by gajop** [comment]
Since it was never implemented, make it a JSON and have userName + engine as fields?
Map/game is redundant as it'll be verified on connection. That existance should be verified beforehand. (It could be an optional parameter though..?)
Engine is only needed because it's used to connect.
PS: Imo, in the future please don't add documentation to the LobbyProtocol of stuff that isn't implemented on uberserver (or any protocol-abiding alternative which might exist).

**Comment by abma** [comment]
> Since it was never implemented, make it a JSON and have userName + engine as fields?
yes!

>Map/game is redundant as it'll be verified on connection. That existance should be verified beforehand. (It could be an optional parameter though..?)

agreed, if its checked beforehand its not needed.
>  PS: Imo, in the future please don't add documentation to the LobbyProtocol of stuff that isn't implemented on uberserver (or any protocol-abiding alternative which might exist).

yep, its confusing for others and more work, agreed as well.

**Comment by abma** [comment]
for the reference: https://github.com/spring/LobbyProtocol/commit/4566c55f30aecfd3b17c92933c28d22e7eb26a5d

**Comment by silentwings** [comment]
CONNECTUSER was removed, can close
